Server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  datasource:
    username: root
    password: Binh!190998
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html

