Server:
  servlet:
    context-path: /api/v1
  port: 8080
spring:
  datasource:
    username: root
    password: Binh!190998
    url: jdbc:mysql://localhost:3307/store-book
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html

